services:
  # PHP-FPM Service
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: rickmorty_php
    volumes:
      - .:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - rickmorty_network
    depends_on:
      - node

  # Nginx Service
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: rickmorty_nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - rickmorty_network

  # Node Service (para TailwindCSS build)
  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    container_name: rickmorty_node
    volumes:
      - .:/var/www/html
      - /var/www/html/node_modules
    working_dir: /var/www/html
    networks:
      - rickmorty_network
    tty: true

networks:
  rickmorty_network:
    driver: bridge
